twig:
    default_path: '%kernel.project_dir%/application/Locodio/Infrastructure/Web/Templates'
    paths:
        '%kernel.project_dir%/application/Lodocio/Infrastructure/Web/Templates': lodocio

when@test:
    twig:
        strict_variables: true
