@startuml

skinparam shadowing false

package "App\Locodio\Domain\Model\Model"{
	class DomainModel {
		id: integer
		uuid: uuid
		name: string
		namespace: string
		repository: string
		{method} Attributes
		{method} Associations
		{method} Enums
		{method} Querys
		{method} Commands
	}
}
package "App\Locodio\Domain\Model\Model"{
	class Attribute {
		id: integer
		uuid: uuid
		name: string
		type: enum
		length: integer
		identifier: boolean
		required: boolean
		make: boolean
		change: boolean
		{method} DomainModel
		{method} Enum
	}
}
package "App\Locodio\Domain\Model\Model"{
	class Association {
		id: integer
		uuid: uuid
		type: enum
		mappedBy: string
		inversedBy: string
		fetch: enum
		orderField: string
		orderDirection: enum
		make: boolean
		change: boolean
		required: boolean
		{method} DomainModel
	}
}
package "App\Locodio\Domain\Model\Model"{
	class Enum {
		id: integer
		uuid: uuid
		name: string
		namespace: string
		{method} DomainModel
		{method} Attributes
		{method} EnumOptions
	}
}
package "App\Locodio\Domain\Model\Model"{
	class EnumOption {
		id: integer
		uuid: uuid
		code: string
		value: string
		{method} Enum
	}
}
package "App\Locodio\Domain\Model\Model"{
	class Query {
		id: integer
		uuid: uuid
		name: string
		namespace: string
		mapping: json
		{method} DomainModel
	}
}
package "App\Locodio\Domain\Model\Model"{
	class Command {
		id: integer
		uuid: uuid
		name: string
		namespace: string
		mapping: json
		{method} DomainModel
	}
}
package "App\Locodio\Domain\Model\Model"{
	enum FetchType {
		EAGER
		LAZY
		EXTRA_LAZY
	}
}
package "App\Locodio\Domain\Model\Model"{
	enum OrderType {
		ASC
		DESC
	}
}
package "App\Locodio\Domain\Model\Model"{
	enum AssociationType {
		MTOU
		OTOU
		OTOB
		OTOS
		OTMB
		OTMS
		MTMU
		MTMB
		MTMS
	}
}
package "App\Locodio\Domain\Model\Model"{
	enum AttributeType {
		INTEGER
		FLOAT
		STRING
		TEXT
		BOOLEAN
		DATE
		DATE_IMMUTABLE
		DATE_TIME
		DATE_TIME_IMMUTABLE
		ARRAY
		SIMPLE_ARRAY
		JSON
		EMAIL
		ENUM
	}
}

AttributeType...> Attribute
AssociationType...> Association
FetchType...> Association
OrderType...> Association
DomainModel "1" *--> "..*" Attribute
DomainModel "1" *--> "..*" Association
DomainModel "1" *--> "..*" Enum
DomainModel "1" *--> "..*" Query
DomainModel "1" *--> "..*" Command
Enum "1" *--> "..*" Attribute
Enum "1" *--> "..*" EnumOption

@enduml